name: speedsive-env
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - ca-certificates=2022.6.15
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfgv=3.3.1
  - distlib=0.3.5
  - editdistance-s=1.0.0
  - filelock=3.7.1
  - flake8=3.8.2
  - identify=2.3.7
  - importlib-metadata=4.11.3
  - libcxx=12.0.0
  - libffi=3.4.2
  - mccabe=0.6.1
  - mypy=0.910
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nodeenv=1.7.0
  - openssl=1.1.1q
  - pip=22.1.2
  - pre-commit=2.15.0
  - pre_commit=2.15.0
  - psutil=5.9.0
  - pycodestyle=2.6.0
  - pycparser=2.21
  - pyflakes=2.2.0
  - python=3.9.12
  - python_abi=3.9
  - pyyaml=6.0
  - readline=8.1.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - toml=0.10.2
  - typing_extensions=4.1.1
  - tzdata=2022a
  - virtualenv=20.4.7
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - moviepy=1.0.3
  - pytube=12.1.0
  - pydub=0.25.1
  - pyflakes=2.2.0
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.12
  - python_abi=3.9
  - pytube=12.1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tbb=2021.5.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tqdm=4.64.0
  - typed-ast=1.5.4
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - ucrt=10.0.20348.0
  - uritemplate=4.1.1
  - urllib3=1.26.10
  - vc=14.2
  - virtualenv=20.4.7
  - vs2015_runtime=14.29.30037
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - decorator==4.4.2
    - proglog==0.1.10
