name: speedsive-env
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - ca-certificates=2022.6.15
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfgv=3.3.1
  - distlib=0.3.5
  - editdistance-s=1.0.0
  - filelock=3.7.1
  - flake8=3.8.2
  - identify=2.3.7
  - importlib-metadata=4.11.3
  - libcxx=12.0.0
  - libffi=3.4.2
  - mccabe=0.6.1
  - mypy=0.910
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nodeenv=1.7.0
  - openssl=1.1.1q
  - pip=22.1.2
  - pre-commit=2.15.0
  - pre_commit=2.15.0
  - psutil=5.9.0
  - pycodestyle=2.6.0
  - pycparser=2.21
  - pyflakes=2.2.0
  - python=3.9.12
  - python_abi=3.9
  - pyyaml=6.0
  - readline=8.1.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - toml=0.10.2
  - typing_extensions=4.1.1
  - tzdata=2022a
  - virtualenv=20.4.7
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - moviepy=1.0.3
  - pytube=12.1.0
  - pydub=0.25.1