name: speedsive-env
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - appdirs=1.4.4
  - async-timeout=4.0.2
  - attrs=21.4.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - cachetools=5.0.0
  - certifi=2022.6.15
  - cffi=1.14.6
  - cfgv=3.3.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - colorama=0.4.5
  - cryptography=37.0.1
  - decorator=5.1.1
  - distlib=0.3.5
  - editdistance-s=1.0.0
  - ffmpeg=4.2.2
  - filelock=3.7.1
  - flake8=3.8.2
  - freetype=2.10.4
  - frozenlist=1.3.0
  - google-api-core=2.8.2
  - google-api-python-client=2.53.0
  - google-auth=2.9.1
  - google-auth-httplib2=0.1.0
  - google-auth-oauthlib=0.5.2
  - googleapis-common-protos=1.56.4
  - httplib2=0.20.4
  - identify=2.3.7
  - idna=3.3
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.7
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - libffi=3.4.2
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - mccabe=0.6.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - moviepy=1.0.3
  - multidict=6.0.2
  - mypy=0.910
  - mypy_extensions=0.4.3
  - nodeenv=1.7.0
  - numpy=1.22.3
  - numpy-base=1.22.3
  - oauthlib=3.2.0
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.1.2
  - pre-commit=2.15.0
  - pre_commit=2.15.0
  - proglog=0.1.9
  - protobuf=3.20.1
  - psutil=5.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycparser=2.21
  - pydub=0.25.1
  - pyflakes=2.2.0
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.12
  - python_abi=3.9
  - pytube=12.1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - toml=0.10.2
  - tqdm=4.64.0
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - uritemplate=4.1.1
  - urllib3=1.26.9
  - vc=14.2
  - virtualenv=20.4.7
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
