name: speedsive-env
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - autopep8=1.5.6
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.14.6
  - cfgv=3.3.1
  - charset-normalizer=2.1.0
  - colorama=0.4.5
  - cryptography=37.0.4
  - distlib=0.3.5
  - editdistance-s=1.0.0
  - ffmpeg=4.3.1
  - filelock=3.7.1
  - flake8=3.8.2
  - freetype=2.10.4
  - identify=2.3.7
  - idna=3.3
  - imageio=2.19.3
  - imageio-ffmpeg=0.4.7
  - importlib-metadata=4.11.3
  - intel-openmp=2022.1.0
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.12
  - libffi=3.4.2
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.4.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mccabe=0.6.1
  - mkl=2022.1.0
  - moviepy=1.0.3
  - msys2-conda-epoch=20160418
  - mypy=0.910
  - mypy_extensions=0.4.3
  - nodeenv=1.7.0
  - numpy=1.23.1
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.1.2
  - pre-commit=2.15.0
  - pre_commit=2.15.0
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pycodestyle=2.6.0
  - pycparser=2.21
  - pydub=0.25.1
  - pyflakes=2.2.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - python_abi=3.9
  - pytube=12.1.0
  - pyyaml=6.0
  - requests=2.28.1
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tbb=2021.5.0
  - tk=8.6.12
  - toml=0.10.2
  - tqdm=4.64.0
  - typing_extensions=4.1.1
  - tzdata=2022a
  - ucrt=10.0.20348.0
  - urllib3=1.26.10
  - vc=14.2
  - virtualenv=20.4.7
  - vs2015_runtime=14.29.30037
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - decorator==4.4.2
    - proglog==0.1.10
