version: 1

formatters:
    simple:
        format: '%(levelname)s - %(message)s'
    complex:
        format: '{"time":"%(asctime)s", "module":"%(name)s","line_no":%(lineno)s, "level":"%(levelname)s", "msg":"%(message)s"},'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

    file:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 5
        level: DEBUG
        formatter: complex
        filename : ../speedsive/logs/logs.log

loggers:
    speedsive:   
        level: DEBUG
        handlers: [console, file]
        propagate: yes